name: Build Linux amd64 Binaries

on: [push]

jobs:
  build-linux:
    runs-on: [self-hosted, X64]
    strategy:
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build release binaries
        run: |
          cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rsbench-amd64-release-binary
          path: target/release/rsbench
