name: Build Linux Binaries

on: [push]

jobs:
  build-linux:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build for ${{ matrix.target }}
        run: |
          # Install needed targets
          rustup target add ${{ matrix.target }}

          cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-release-binary
          path: target/${{ matrix.target }}/release/rsbench
