name: Cargo Publish To Crates.io

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  Test:
    name: Cargo Publish To Crates.io - ${{ github.sha }}
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: ./target
          key: publish

      - name: Setup Rust
        uses: moonrepo/setup-rust@v1

      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true