name: Linux Cross Build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  release:
    name: Build - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: linux_x86_64_musl
            target: x86_64-unknown-linux-musl
            binary_name: rsbench-linux-x86_64-musl
          - release_for: linux_x86_64_gnu
            target: x86_64-unknown-linux-gnu
            binary_name: rsbench-linux-x86_64-gnu
          - release_for: linux_arm_gnueabi
            target: arm-unknown-linux-gnueabi
            binary_name: rsbench-linux-arm-gnueabi
          - release_for: linux_arm_gnueabihf
            target: arm-unknown-linux-gnueabihf
            binary_name: rsbench-linux-arm-gnueabihf
          - release_for: linux_aarch64_gnu
            target: aarch64-unknown-linux-gnu
            binary_name: rsbench-linux-aarch64-gnu
          - release_for: linux_aarch64_musl
            target: aarch64-unknown-linux-musl
            binary_name: rsbench-linux-aarch64-musl
          - release_for: linux_i686_gnu
            target: i686-unknown-linux-gnu
            binary_name: rsbench-linux-i686-gnu
          - release_for: linux_i686_musl
            target: i686-unknown-linux-musl
            binary_name: rsbench-linux-i686-musl
          - release_for: linux_arm_musleabi
            target: arm-unknown-linux-musleabi
            binary_name: rsbench-linux-arm-musleabi
          - release_for: linux_arm_musleabihf
            target: arm-unknown-linux-musleabihf
            binary_name: rsbench-linux-arm-musleabihf
          - release_for: linux_armv5te_gnu
            target: armv5te-unknown-linux-gnueabi
            binary_name: rsbench-linux-armv5te-gnueabi
          - release_for: linux_armv5te_musl
            target: armv5te-unknown-linux-musleabi
            binary_name: rsbench-linux-armv5te-musleabi
          - release_for: linux_armv7_gnueabi
            target: armv7-unknown-linux-gnueabi
            binary_name: rsbench-linux-armv7-gnueabi
          - release_for: linux_armv7_gnueabihf
            target: armv7-unknown-linux-gnueabihf
            binary_name: rsbench-linux-armv7-gnueabihf
          - release_for: linux_armv7_musleabi
            target: armv7-unknown-linux-musleabi
            binary_name: rsbench-linux-armv7-musleabi
          - release_for: linux_armv7_musleabihf
            target: armv7-unknown-linux-musleabihf
            binary_name: rsbench-linux-armv7-musleabihf
          - release_for: linux_loongarch64_gnu
            target: loongarch64-unknown-linux-gnu
            binary_name: rsbench-linux-loongarch64-gnu
          - release_for: linux_loongarch64_musl
            target: loongarch64-unknown-linux-musl
            binary_name: rsbench-linux-loongarch64-musl
          - release_for: linux_powerpc_gnu
            target: powerpc-unknown-linux-gnu
            binary_name: rsbench-linux-powerpc-gnu
          - release_for: linux_powerpc64_gnu
            target: powerpc64-unknown-linux-gnu
            binary_name: rsbench-linux-powerpc64-gnu
          - release_for: linux_powerpc64le_gnu
            target: powerpc64le-unknown-linux-gnu
            binary_name: rsbench-linux-powerpc64le-gnu
          - release_for: linux_riscv64gc_gnu
            target: riscv64gc-unknown-linux-gnu
            binary_name: rsbench-linux-riscv64gc-gnu
          - release_for: linux_riscv64gc_musl
            target: riscv64gc-unknown-linux-musl
            binary_name: rsbench-linux-riscv64gc-musl
          - release_for: linux_s390x_gnu
            target: s390x-unknown-linux-gnu
            binary_name: rsbench-linux-s390x-gnu

    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: ./target
          key: ${{ matrix.platform.release_for }}
      - name: Build binary
        uses: moohr/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release --jobs 32"
          strip: true
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - name: Compress binary
        run: upx -v --ultra-brute target/${{ matrix.platform.target }}/release/rsbench
      - name: Rename binary
        run: cp target/${{ matrix.platform.target }}/release/rsbench target/${{ matrix.platform.target }}/release/${{ matrix.platform.binary_name }}
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.target }}
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.binary_name }}