name: Check & Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  Test:
    name: Check & Test - ${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: moonrepo/setup-rust@v1

      - name: Cargo Check
        run: cargo check

      - name: Cargo Test
        run: cargo test