name: Check & Test & Clippy

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  Test:
    name: Check & Test & Clippy - ${{ github.sha }}
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      - name: Cargo Check
        run: cargo check

      - name: Cargo Test
        run: cargo test

      - name: Install Clippy
        run: rustup component add clippy

      - name: Cargo Clippy
        run: cargo clippy